### ISSUE TITLE
fsync install error

### ISSUE THREAD

**Issue by gitaaron** [functionland/fula#196] opened 2022-05-22 18:50 UTC
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/asurty/POpen/fxland/fula/examples/doc-sync/fsync/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! /bin/sh: node-pre-gyp: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asurty/.npm/_logs/2022-05-22T18_45_00_669Z-debug.log
```

**Comment by farhoud** [comment] 2022-05-23 04:21
Mac M1?

**Comment by farhoud** [comment] 2022-05-23 14:46
Oh If I have node-pre-gyp global on my system and i think i miss it!
but if that fail i think uploader most fail too.

**Comment by farhoud** [comment] 2022-06-01 12:01
All this problem has root cause.
https://github.com/node-webrtc/node-webrtc/pull/694
I wish they release soon.
I will close this issue.

**Closed by farhoud** 2022-06-01 12:01 UTC
